package net.onelitefeather.falco.anvil;

import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Contract;

import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.LongAdder;

/**
 * The {@link AnvilDiagnostics} class throttles repeating warnings of a chunk loader and collects
 * the counters which are reported when the loader is closed.
 * <p>
 * A world can hold thousands of chunks which all trigger the same problem, for example a block
 * which the server does not know. Logging that problem once per chunk would flood the log without
 * adding any information, so every report is reduced to the first occurrence of a distinct name.
 * The amount of tracked names is capped because a broken world can contain an unbounded amount of
 * unknown names which would otherwise grow the tracking sets without a limit.
 * </p>
 * <p>
 * Instances are safe to use from multiple threads which is required because a loader reports from
 * every thread that loads or saves a chunk.
 * </p>
 *
 * <p>
 * This type is experimental. The Anvil loader is new and its API may still change while it is
 * being validated against real worlds.
 * </p>
 *
 * @author TheMeinerLP
 * @version 1.0.0
 * @since 0.1.0
 */
@ApiStatus.Experimental
public final class AnvilDiagnostics {

    /**
     * The highest amount of distinct names a single category tracks.
     */
    public static final int MAX_TRACKED_NAMES = 64;

    private final Set<String> unknownBlocks;
    private final Set<String> unknownBiomes;
    private final AtomicBoolean partialChunkReported;
    private final AtomicBoolean sectionRangeReported;
    private final LongAdder chunksLoaded;
    private final LongAdder chunksSaved;
    private final LongAdder errors;

    /**
     * Creates a new diagnostics instance with empty counters.
     */
    public AnvilDiagnostics() {
        this.unknownBlocks = ConcurrentHashMap.newKeySet();
        this.unknownBiomes = ConcurrentHashMap.newKeySet();
        this.partialChunkReported = new AtomicBoolean();
        this.sectionRangeReported = new AtomicBoolean();
        this.chunksLoaded = new LongAdder();
        this.chunksSaved = new LongAdder();
        this.errors = new LongAdder();
    }

    /**
     * Checks whether an unknown block name should be reported.
     * Only the first occurrence of a name passes so a repeating problem does not flood the log.
     *
     * @param name the name of the unknown block
     * @return true if the caller should log the name, otherwise false
     */
    public boolean reportUnknownBlock(String name) {
        return track(this.unknownBlocks, name);
    }

    /**
     * Checks whether an unknown biome name should be reported.
     * Only the first occurrence of a name passes so a repeating problem does not flood the log.
     *
     * @param name the name of the unknown biome
     * @return true if the caller should log the name, otherwise false
     */
    public boolean reportUnknownBiome(String name) {
        return track(this.unknownBiomes, name);
    }

    /**
     * Checks whether a partially generated chunk should be reported.
     * A world which was generated by another server can hold many of them, so the report happens
     * only once for the lifetime of the loader.
     *
     * @return true if the caller should log the problem, otherwise false
     */
    public boolean reportPartialChunk() {
        return this.partialChunkReported.compareAndSet(false, true);
    }

    /**
     * Checks whether a section outside of the dimension height should be reported.
     *
     * @return true if the caller should log the problem, otherwise false
     */
    public boolean reportSectionOutOfRange() {
        return this.sectionRangeReported.compareAndSet(false, true);
    }

    /**
     * Counts a chunk which was loaded successfully.
     */
    public void countChunkLoaded() {
        this.chunksLoaded.increment();
    }

    /**
     * Counts a chunk which was saved successfully.
     */
    public void countChunkSaved() {
        this.chunksSaved.increment();
    }

    /**
     * Counts a chunk which could not be loaded or saved.
     */
    public void countError() {
        this.errors.increment();
    }

    /**
     * Returns the amount of chunks which were loaded successfully.
     *
     * @return the amount of loaded chunks
     */
    @Contract(pure = true)
    public long chunksLoaded() {
        return this.chunksLoaded.sum();
    }

    /**
     * Returns the amount of chunks which were saved successfully.
     *
     * @return the amount of saved chunks
     */
    @Contract(pure = true)
    public long chunksSaved() {
        return this.chunksSaved.sum();
    }

    /**
     * Returns the amount of chunks which could not be loaded or saved.
     *
     * @return the amount of failed chunks
     */
    @Contract(pure = true)
    public long errors() {
        return this.errors.sum();
    }

    /**
     * Returns the amount of distinct unknown block names which were reported.
     *
     * @return the amount of unknown block names
     */
    @Contract(pure = true)
    public int unknownBlockCount() {
        return this.unknownBlocks.size();
    }

    /**
     * Returns the amount of distinct unknown biome names which were reported.
     *
     * @return the amount of unknown biome names
     */
    @Contract(pure = true)
    public int unknownBiomeCount() {
        return this.unknownBiomes.size();
    }

    /**
     * Adds the given name to the tracking set as long as the cap is not reached yet.
     *
     * @param names the set which tracks the names of a category
     * @param name  the name to track
     * @return true if the name was added by this call, otherwise false
     */
    private static boolean track(Set<String> names, String name) {
        // The size check and the insertion cannot be one atomic step on a set, so racing threads
        // could push it past the cap. A slightly relaxed bound is acceptable here because the cap
        // exists to protect the heap, not to be an exact quota, but the set is trimmed back so it
        // cannot drift upwards over time.
        if (names.size() >= MAX_TRACKED_NAMES) {
            return false;
        }
        if (!names.add(name)) {
            return false;
        }
        if (names.size() > MAX_TRACKED_NAMES) {
            names.remove(name);
            return false;
        }
        return true;
    }
}
